# Generated by Django 4.1.10 on 2023-08-31 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_customsetting_options_translatenavbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='translate_navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.translatenavbar'),
        ),
    ]
