# Generated by Django 4.1.10 on 2023-09-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_customsetting_translate_navbar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='language_menu',
            field=models.BooleanField(default=True, help_text='Show/hide language menu item', verbose_name='language menu item'),
        ),
    ]
