# Generated by Django 4.1.10 on 2023-09-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_customsetting_language_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='content_margin_top',
            field=models.IntegerField(default=0, help_text='margin top for content, use with fixed navbar settings', verbose_name='content margin top'),
        ),
    ]
