# Generated by Django 4.1.10 on 2023-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_customsetting_content_margin_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='footer_bg_color',
            field=models.CharField(blank=True, help_text='footer background color value', max_length=500, null=True, verbose_name='footer background color'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='content_margin_top',
            field=models.IntegerField(default=0, help_text='margin top for content, use with fixed navbar settings', verbose_name='content margin top (px)'),
        ),
    ]
