# Generated by Django 4.1.10 on 2023-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_customsetting_footer_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='nav_bg_color',
            field=models.CharField(blank=True, help_text='Navbar background color value', max_length=500, null=True, verbose_name='Navbar background color'),
        ),
    ]
