# Generated by Django 4.1.10 on 2023-09-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_customsetting_nav_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='footer_text_color',
            field=models.CharField(blank=True, help_text='Footer text color value', max_length=500, null=True, verbose_name='Footer text color'),
        ),
    ]
