# Generated by Django 4.1.13 on 2023-11-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_customsetting_facebook_page_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsetting",
            name="using_whatsapp",
            field=models.BooleanField(
                default=True,
                help_text="Show/hide whatsapp chat support",
                verbose_name="whatsapp page chat support",
            ),
        ),
        migrations.AddField(
            model_name="customsetting",
            name="whatsapp_id",
            field=models.CharField(
                blank=True,
                help_text="Your whatsapp id",
                max_length=255,
                verbose_name="whatsapp id",
            ),
        ),
        migrations.AlterField(
            model_name="customsetting",
            name="facebook_page_id",
            field=models.CharField(
                blank=True,
                help_text="Your facebook page id",
                max_length=255,
                verbose_name="page id",
            ),
        ),
        migrations.AlterField(
            model_name="customsetting",
            name="using_messenger",
            field=models.BooleanField(
                default=True,
                help_text="Show/hide facebook messenger chat support",
                verbose_name="messenger page",
            ),
        ),
    ]
