# Generated by Django 4.1.13 on 2023-11-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_customsetting_using_whatsapp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customsetting",
            name="facebook_page_id",
            field=models.CharField(
                blank=True,
                help_text="Your facebook page id",
                max_length=255,
                verbose_name="facebook page id",
            ),
        ),
        migrations.AlterField(
            model_name="customsetting",
            name="using_messenger",
            field=models.BooleanField(
                default=True,
                help_text="Show/hide facebook messenger chat support",
                verbose_name="using facebook messenger chat support",
            ),
        ),
        migrations.AlterField(
            model_name="customsetting",
            name="using_whatsapp",
            field=models.BooleanField(
                default=True,
                help_text="Show/hide whatsapp chat support",
                verbose_name="using whatsapp chat support",
            ),
        ),
    ]
