# Generated by Django 4.1.13 on 2023-11-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_alter_customsetting_facebook_page_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsetting",
            name="email_backend",
            field=models.CharField(
                blank=True,
                help_text="Your Email Backend",
                max_length=255,
                verbose_name="EMAIL_BACKEND",
            ),
        ),
        migrations.AddField(
            model_name="customsetting",
            name="email_host",
            field=models.CharField(
                blank=True,
                help_text="Your Email Host",
                max_length=255,
                verbose_name="EMAIL_HOST",
            ),
        ),
        migrations.AddField(
            model_name="customsetting",
            name="email_host_password",
            field=models.CharField(
                blank=True,
                help_text="Your Email Host Password",
                max_length=255,
                verbose_name="EMAIL_HOST_PASSWORD",
            ),
        ),
        migrations.AddField(
            model_name="customsetting",
            name="email_host_user",
            field=models.EmailField(
                help_text="Your Email Host User",
                max_length=254,
                null=True,
                verbose_name="EMAIL_HOST_USER",
            ),
        ),
        migrations.AddField(
            model_name="customsetting",
            name="email_port",
            field=models.PositiveIntegerField(
                default=0, help_text="Your Email Port", verbose_name="EMAIL_PORT"
            ),
        ),
        migrations.AddField(
            model_name="customsetting",
            name="email_use_tls",
            field=models.BooleanField(
                default=True,
                help_text="Your Email Use TLS",
                verbose_name="EMAIL_USE_TLS",
            ),
        ),
        migrations.AddField(
            model_name="customsetting",
            name="owner_mail",
            field=models.EmailField(
                help_text="Owner Mail",
                max_length=254,
                null=True,
                verbose_name="Owner Mail",
            ),
        ),
    ]
