# Generated by Django 4.1.13 on 2023-12-06 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0015_customsetting_email_backend_customsetting_email_host_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customsetting",
            name="email_backend",
        ),
    ]
