# Generated by Django 4.1.13 on 2023-12-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_remove_customsetting_email_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customsetting",
            name="email_host_user",
            field=models.CharField(
                blank=True,
                default=1,
                help_text="Your Email Host User",
                max_length=255,
                verbose_name="EMAIL_HOST_USER",
            ),
            preserve_default=False,
        ),
    ]
