# Generated by Django 4.1.13 on 2023-12-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_alter_customsetting_email_host_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsetting",
            name="email_sender",
            field=models.EmailField(
                help_text="Your email sender",
                max_length=254,
                null=True,
                verbose_name="Email Sender",
            ),
        ),
    ]
