# Generated by Django 4.0.8 on 2023-12-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_locationmarker_alter_articleindexpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmarker',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='locationmarker',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
