# Generated by Django 4.0.8 on 2023-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_locationmarker_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmarker',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
