# Generated by Django 4.0.8 on 2023-12-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_locationmarker_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmarker',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locationmarker',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
