# Generated by Django 4.0.8 on 2023-12-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_locationindexpage_locationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
