# Generated by Django 4.1.10 on 2023-12-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('website', '0031_alter_locationpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail image'),
        ),
    ]
