# Generated by Django 4.1.13 on 2024-10-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0039_alter_classifierterm_slug'),
        ('website', '0034_navbarsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManagementPage',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.coderedpage')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Document Management Page',
            },
            bases=('coderedcms.coderedpage',),
        ),
    ]
