# Generated by Django 4.1.13 on 2024-10-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_documentmanagementpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataPage',
            fields=[
                ('documentmanagementpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.documentmanagementpage')),
            ],
            options={
                'verbose_name': 'Training Data Page',
            },
            bases=('website.documentmanagementpage',),
        ),
    ]
