# Generated by Django 4.1.13 on 2024-10-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_trainingdatapage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingDataPage',
            new_name='DownloadDataPage',
        ),
    ]
