# Generated by Django 4.1.13 on 2024-10-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_rename_trainingdatapage_downloaddatapage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloaddatapage',
            options={'verbose_name': 'Download Data Page'},
        ),
    ]
